apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server4.name }}
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: {{ .Values.server4.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.server4.name }}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: {{ .Values.server4.name}}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - env:
            - name: NAME
              value: {{ .Values.server4.name }}
            - name: PORT
              value: "{{ .Values.server4.service.port}}"
          image: "{{ .Values.server4.image.repository }}:{{ .Values.server4.image.tag | default .Chart.AppVersion }}"
          name: {{ .Values.server4.name }}
          imagePullPolicy: {{ .Values.server4.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.server4.service.port}}
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
