apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.proxy.name }}
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: {{ .Values.proxy.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.proxy.name }}
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: proxy
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.proxy.name }}
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.proxy.service.port}}
          resources: {}
      hostname: {{ .Values.proxy.name}}
      restartPolicy: {{ .Values.restartPolicy }}
