apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server1.name }}
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: {{ .Values.server1.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.server1.name }}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: {{ .Values.server1.name}}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - env:
          - name: NAME
            value: {{ .Values.server1.name }}
          - name: PORT
            value: "{{ .Values.server1.service.port}}"
          image: "{{ .Values.server1.image.repository }}:{{ .Values.server1.image.tag | default .Chart.AppVersion }}"
          name: {{ .Values.server1.name }}
          imagePullPolicy: {{ .Values.server1.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.server1.service.port}}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
      restartPolicy: {{ .Values.restartPolicy }}
