apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: generator
  name: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: generator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/resolute: "true"
        io.kompose.service: generator
    spec:
      containers:
        - name: generator
          image: horizontal_k8s_generator:latest
          imagePullPolicy: "Never"
          ports:
          - containerPort: 8089
          resources: {}
      hostname: generator
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
