apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: generator
  name: generator
spec:
  type: LoadBalancer
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8089
  selector:
    io.kompose.service: generator
status:
  loadBalancer: {}
