apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/resolute: "true"
        io.kompose.service: proxy
    spec:
      containers:
        - name: proxy
          image: horizontal_k8s_proxy:latest
          imagePullPolicy: "Never"
          ports:
          - containerPort: 8090
          resources: {}
      hostname: proxy
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
