apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: server2
  name: server2
spec:
  ports:
  - name: "8092"
    port: 8092
    targetPort: 8092
  selector:
    io.kompose.service: server2
