apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: server3
  name: server3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server3
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/resolute: "true"
        io.kompose.service: server3
    spec:
      containers:
      - env:
        - name: NAME
          value: server3
        - name: PORT
          value: "8093"
        image: horizontal_k8s_server3:latest
        imagePullPolicy: "Never"
        name: server3
        ports:
        - containerPort: 8093
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
