apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: server4
  name: server4
spec:
  ports:
  - name: "8094"
    port: 8094
    targetPort: 8094
  selector:
    io.kompose.service: server4
